/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_NbodySimulator_SimDataModel */

#ifndef _Included_com_NbodySimulator_SimDataModel
#define _Included_com_NbodySimulator_SimDataModel
#ifdef __cplusplus
extern "C" {
#endif
#undef com_NbodySimulator_SimDataModel_NUM_P
#define com_NbodySimulator_SimDataModel_NUM_P 5L
#undef com_NbodySimulator_SimDataModel_LEN_FOOTPRINT
#define com_NbodySimulator_SimDataModel_LEN_FOOTPRINT 1000L
/*
 * Class:     com_NbodySimulator_SimDataModel
 * Method:    ndk_calcForce
 * Signature: ([D[D[D[D[IID)V
 */
JNIEXPORT void JNICALL Java_com_NbodySimulator_SimDataModel_ndk_1calcForce
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jintArray, jint, jdouble);

/*
 * Class:     com_NbodySimulator_SimDataModel
 * Method:    ndk_integrate
 * Signature: ([D[D[DID)V
 */
JNIEXPORT void JNICALL Java_com_NbodySimulator_SimDataModel_ndk_1integrate
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
